# Elasticsearch configuration
ongr_elasticsearch:
    connections:
        default:
            index_name: error_retention
    managers:
        default:
            connection: default
            mappings:
                - AppBundle

# Elasticsearch endpoint api
ongr_api:
#    default_encoding: json
    versions:
        v1:
            endpoints:
                error:
                    repository: es.manager.default.error
                    methods: ["GET", "POST"]
                    allow_extra_fields: true
                    allow_batch: true
                    allow_get_all: true

# Error filters
ongr_filter_manager:
    managers:
        search_list: # <- Filter manager name
            filters:
                - method
                - user
                - app
                - env
#                - occurred
                - message
                - url
                - error_class
                - search_pager
                - search_sort
            repository: 'es.manager.default.error'
    filters:
        multi_choice:
            method:
                request_field: 'method'
                field: method
            app:
                request_field: 'app'
                field: app
            env:
                request_field: 'env'
                field: env
        match:
            error_class:
                request_field: 'errorClass'
                field: errorClass
            url:
                request_field: 'url'
                field: url
            message:
                request_field: 'message'
                field: message
            user:
                request_field: 'user'
                field: user
        pager:
            search_pager:
                request_field: 'page'
                count_per_page: 10
        sort:
            search_sort:
                request_field: 'sort'
                choices:
                  - { label: Search score, key: score, field: _score }
                  - { label: Older, key: occurred_asc, field: occurred, order: asc }
                  - { label: Newer, key: occurred_desc, field: occurred, order: desc, default: true }