# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

# RAD services definition
services:

    # Date Diff extension
    app.twig.extension.date:
        class:        Twig_Extensions_Extension_Date
        tags:
             - { name: 'twig.extension' }

    # MongoDB provider service
    mongodb_provider:
        class: AppBundle\Service\MongoDBService
        arguments: ["mongodb://localhost:27017", "error"]

    # Subscriber for KnpPaginatorBundle
    subscriber_mongodb_pager:
        class: AppBundle\Subscriber\PaginateMongodbSubscriber
        arguments: ['@mongodb_provider']
        tags:
            - { name: knp_paginator.subscriber }

    # Application exception listener - logs all application exceptions
    erkam.exception_listener:
        class: AppBundle\EventListener\ExceptionListener
        arguments: ['@erkam.service']
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    # Main application service to handle all local actions
    erkam.service:
        class: AppBundle\Service\ErkamService
        arguments: ['@request_stack']
        calls:
            - ['setProvider', ['@mongodb_provider']]

#    erkam.search.service:
#        class: AppBundle\Service\SearchService
#        arguments: ['@es.manager.default.error']

#    ongr_filter_manager:
#        cache:
#            engine: 'es.cache_engine' # cache engine, set null to disable caching
#            life_time: 1080 # cache life time in seconds, 3 hours default
#            exclude:
#                - search